python -m unittest test_api.TestApi.test_face_compare
python -m unittest test_api.TestApi.test_face_otp
python -m unittest test_api.TestApi.test_insert_manual
python -m unittest test_api.TestApi.test_search_manual
python -m unittest test_api.TestApi.test_face_register
python -m unittest test_api.TestApi.test_face_search
python -m unittest test_api.TestApi.test_face_search_v2
python -m unittest test_api.TestApi.test_face_remove
python -m unittest test_api.TestApi.test_face_live
python -m unittest test_api.TestApi.test_face_fake
